### ISSUE TITLE
Optimizer

### ISSUE THREAD

**Issue by mattcroberts** [blai/require-dust#1]
Hi,

I've checked out the demo and dynamic loading works as expected however the optimizer functionality doesn't seem to work.

Running the build script runs the optimizer but does not optimize the dust template. Is this project still maintained?

Regards,
Matt

**Comment by blai** [comment]
@mattcroberts This was an early prototype for a bigger system I develop for my company. I would like to maintain and enhance this. Can you provide a sample project on github so I can study your use case? It's been a while I touched this so I will need to refresh myself a bit :)

**Comment by PredokMiF** [comment]
@mattcroberts I create [sample](https://github.com/PredokMiF/rjs_dust) with r.js optimize, maybe it will be interesting for you. I have to change [require-dust.js](https://github.com/blai/require-dust/blob/master/require-dust.js), because dependenced was broken (maybe only for me).

@blai Is it still interesting for you?! )))

**Comment by blai** [comment]
@mattcroberts new technologies are available nowadays that I suggest you use those instead:
- [webpack](https://webpack.github.io/)
- [browserify](http://browserify.org/)
- [bower](http://bower.io/)

**Comment by PredokMiF** [comment]
This is good, but with RequireJS I can load compiled core libs and layzy load another js files (what I need now, not all).
Dev mode: With RequireJS I can change file and replace with [Fiddler](http://www.telerik.com/fiddler). Webpack need to compile sources anyway.

**Comment by blai** [comment]
@PredokMiF if only that is your requirement, then https://github.com/systemjs/systemjs is your new answer :)
